#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           Claw,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           Winch,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           Servo1,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"


void pre_auton()//autonomous init - runs once
{
  bStopTasksBetweenModes = true;

}


task autonomous() //autonomous code
{

}

task usercontrol()//teleop
{


  while (true) //infinite loop
  {
   	motor[leftMotor] = vexRT[Ch2];
		motor[rightMotor] = vexRT[Ch3];

		if (vexRT[Btn8U]){
			motor[Servo1] = 240;
		}
		if (vexRT[Btn8D]){
			motor[Servo1] = 0;
		}

		if (vexRT[Btn7U]){
			motor[Winch] = 127;
		}
		else if (vexRT[Btn7D]) {
			motor[Winch] = -127;
		}
		else {
			motor[Winch] = 0;
		}

		if (vexRT[Btn7L]) {
			motor[Claw] = 127;
		}
		else if (vexRT[Btn7R]) {
			motor[Claw] = -127;
		}
		else {
			motor[Claw] = 0;
		}
  }
}
